# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name_plural': 'Log entries'},
        ),
    ]
